languageCode: en-us
title: "Tushar Gupta"
enableRobotsTXT: false
enableGitInfo: true

# Use Hugo modules to add theme
module:
  imports:
  - path: github.com/tgupta3/toha/v4
  mounts:
  - source: ./node_modules/flag-icon-css/flags
    target: static/flags
  - source: ./node_modules/@fontsource/mulish/files
    target: static/files
  - source: ./node_modules/katex/dist/fonts
    target: static/fonts


# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1

# Allow raw html in markdown file
markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON

# Enable global emoji support
enableEmoji: true

params:
  # GitHub repo URL of your site
  gitRepo: https://github.com/tgupta3/tgupta.me
  # Default branch of your Git repo
  gitBranch: main

  # Configure the number of section title visible in the top navbar
  topNavbar:
    maxVisibleSections: 5
  
  # specify whether you want to write some blog posts or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true
  
  features:
    
    darkMode:
      enable: true
  
    analytics:
      enable: false
  
     # Enable and configure portfolio
    portfolio:
      enable: true
    
    # Enable and configure blog posts
    blog:
      enable: true
      # Share post on different social media
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        reddit: true
        whatsapp: true
        email: true

  footer:
    enable: true
    navigation:
      enable: false
    newsletter:
      enable: false
    contactMe:
      enable: false
    disclaimer:
      enable: true
    credentials:
      enable: true