version: 0.1
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
      - pip install boto3
      - serverless plugin install -n serverless-s3-sync

  build:
    commands:
      - serverless deploy --verbose
