service: tgupta

plugins:
  - serverless-s3-sync

provider:
  name: aws
  runtime: python2.7
  region: us-east-1
  stage: dev

package:
  exclude:
    - node_modules/
    - README.md

custom:
    stage: ${opt:stage, self:provider.stage}
    bucketspec: ${file(bucket_spec.yml):${self:custom.stage}}
    s3Sync:
      - bucketName: ${self:custom.bucketspec.BUCKET}
        localDir: tgupta.me1/
