version: 0.1
phases:
  install:
    commands:
      - pip install boto3
      - pip install awscli

  pre_build:
    commands:
      - aws s3api head-bucket --bucket prod.tgupta.me

  build:
    commands:
      - aws s3 sync tgupta.me/ s3://prod.tgupta.me
