version: 0.1
phases:
  install:
    commands:
      - pip install --upgrade pip 
      - pip install boto3
      - pip install awscli


  pre_build:
    commands:
      - aws s3api head-bucket --bucket staging.tgupta.me

  build:
    commands:
      - aws s3 sync tgupta.me/ s3://staging.tgupta.me
